### ISSUE TITLE
Update hex version

### ISSUE THREAD

**Issue by sivsushruth** [ninenines/cowlib#43]
Hey, 
following this commit, https://github.com/ninenines/cowlib/commit/a7d5141d13c8944867c9361e544981d9954728c4#diff-5b3b33d473fd0bc66ff7e18709099694L427

I see that the hex package does not have this commit, as a result the make task fails on OTP 19. Here is the log:

```
Sushruths-MacBook-Pro:barrel-platform sivsushruth$ MIX_DEBUG=1 mix compile
** Running mix loadconfig (inside Barrel.Mixfile)
** Running mix compile (inside Barrel.Mixfile)
** Running mix loadpaths (inside Barrel.Mixfile)
** Running mix archive.check (inside Barrel.Mixfile)
** Running mix deps.check (inside Barrel.Mixfile)
** Running mix deps.precompile (inside Barrel.Mixfile)
==> cowlib
 ERLC   cow_cookie.erl cow_date.erl cow_http.erl cow_http_hd.erl cow_http_te.erl cow_mimetypes.erl cow_multipart.erl cow_qs.erl cow_spdy.erl
compile: warnings being treated as errors
src/cow_multipart.erl:392: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
make[1]: *** [ebin/cowlib.app] Error 1
make: *** [all] Error 2
** (Mix.Error) Could not compile dependency :cowlib, "make" command failed. You can recompile this dependency with "mix deps.compile cowlib", update it with "mix deps.update cowlib" or clean it with "mix deps.clean cowlib"
    (mix) lib/mix.ex:274: Mix.raise/1
    (mix) lib/mix/project.ex:211: Mix.Project.in_project/4
    (elixir) lib/file.ex:1145: File.cd!/2
    (mix) lib/mix/dep.ex:173: Mix.Dep.in_dependency/3
    (mix) lib/mix/tasks/deps.compile.ex:206: Mix.Tasks.Deps.Compile.do_command/5
    (mix) lib/mix/tasks/deps.compile.ex:76: anonymous fn/4 in Mix.Tasks.Deps.Compile.compile/2
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/deps.compile.ex:65: Mix.Tasks.Deps.Compile.compile/2

```

I feel version number needs update and republished to hex. 
Thoughts @essen  ?

**Comment by Gazler** [comment]
@sivsushruth I believe the latest version (1.3.0) is available in hex https://hex.pm/packages/cowlib/1.3.0

Perhaps you need to override it in your mix.exs file:

      {:cowlib, "~> 1.3.0", override: true},

**Comment by sivsushruth** [comment]
@Gazler Thanks, I am checking

**Comment by essen** [comment]
Cowlib 1.3 is not compatible with Cowboy 1.0.

Also nothing is broken, it's just a warning and warnings are ignored when used as dependency, so if it fails then it means Mix doesn't compile Cowlib properly. The command to compile it should be "make -C path/to/cowlib IS_DEP=1".

**Comment by essen** [comment]
Good to know, thanks.

**Comment by sivsushruth** [comment]
Thanks a ton guys. That helped a lot. Problem solved. 
@esses @ericmj
